os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD: https://api.bintray.com/conan/sixten-hilborn/conan
    - CONAN_REFERENCE="emscripten-fastcomp/*"
    - CONAN_USERNAME="hilborn"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

  matrix:
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
matrix:
   include:
       - os: osx
         osx_image: xcode8.3
         language: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
  
